apiVersion: v1
kind: Pod
metadata:
  name: picassodb
  labels:
    zone: prod
    version: v1
spec:
  containers:
    - name: picassodb   
      image: postgres
      ports: 
        # - containerPort: 5439
        - protocol: TCP
            port: 5439
            targetPort: 5432
      env:
        - name: POSTGRES_DB
          value:  Picasso
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: pswPicasso